# Generated by Django 6.0 on 2026-01-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housecrew',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
