# Generated by Django 6.0 on 2026-01-15 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_housecrew_is_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addservices',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.s_category'),
        ),
    ]
