# Generated by Django 6.0 on 2026-01-15 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_addservices_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addservices',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.housecrew'),
        ),
    ]
