# Generated by Django 6.0 on 2026-01-16 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_addservices_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='addservices',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.s_category'),
        ),
    ]
