# Generated by Django 6.0 on 2026-01-16 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_addservices_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addservices',
            name='service_type',
        ),
        migrations.AddField(
            model_name='addservices',
            name='crew',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='admin_app.housecrew'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addservices',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='admin_app.s_category'),
        ),
    ]
