# Generated by Django 6.0 on 2026-01-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_remove_addservices_service_type_addservices_crew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addservices',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
