# Generated by Django 6.0 on 2026-01-12 17:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='S_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(error_messages={'unique': 'This company already exists'}, max_length=100, unique=True, verbose_name='Company Name')),
                ('c_registration', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Enter CIN registration. (eg: L12345KL2023PLC123456)', regex='^[LU]\\d{5}(KL)\\d{4}(PVT|PLC|LLP|OPC)\\d{6}$')])),
                ('c_mobile_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number', regex='^[6-9]\\d{9}$')])),
                ('c_email_id', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email')])),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('is_active', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('can_resubmit', models.BooleanField(default=False)),
                ('c_service_location', models.ManyToManyField(related_name='companies', to='admin_app.location')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='C_profile_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_year', models.CharField(choices=[('1', '1 years'), ('2', '2 years'), ('3', '3 years'), ('4', '4 years'), ('5', '5 years'), ('5+', 'More than 5 years')], max_length=20)),
                ('c_wportfolio', models.FileField(blank=True, null=True, upload_to='wrok_portfolios/')),
                ('c_nature_service', models.ManyToManyField(related_name='nature_of_services', to='admin_app.s_category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_profiles', to='company_app.s_company')),
            ],
        ),
        migrations.CreateModel(
            name='C_legal_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_pan', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN number (eg: ABCDE1234S)', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')])),
                ('c_gst', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid GST number (eg: 22ABCDE1234F1Z5)', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_registration', to='company_app.s_company')),
            ],
        ),
        migrations.CreateModel(
            name='C_insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_ins_type', models.CharField(choices=[('LIABILITY', 'Liability'), ('WORKMEN', 'Workmen Compensation'), ('EQUIPMENT', 'Equipment')], max_length=20)),
                ('c_ins_provider', models.CharField(max_length=30)),
                ('c_ins_number', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='company_app.s_company')),
            ],
        ),
        migrations.CreateModel(
            name='C_declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_p_verification', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('c_noc', models.FileField(blank=True, null=True, upload_to='company_noc/')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declaration', to='company_app.s_company')),
            ],
        ),
        migrations.CreateModel(
            name='C_chief_technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_chief_name', models.CharField(max_length=30)),
                ('c_chief_role', models.CharField(choices=[('SUPERVISOR', 'CHIEF SUPERVISOR'), ('TECH_LEAD', 'TECHNICAL LEAD'), ('OPS_HEAD', 'OPERATION HEAD'), ('SITE_HEAD', 'SITE HEAD'), ('SERVICE_MANAGER', 'SERVICE MANAGER')], max_length=20)),
                ('c_chief_exp', models.CharField(choices=[('2', '2 years'), ('2+', 'More than 2 years')], max_length=10)),
                ('c_chief_contact', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number', regex='^[6-9]\\d{9}$')])),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chief_technician', to='company_app.s_company')),
            ],
        ),
        migrations.CreateModel(
            name='Auth_personal_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_p_name', models.CharField(max_length=50)),
                ('auth_p_designation', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], max_length=20)),
                ('auth_p_mobile_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number', regex='^[6-9]\\d{9}$')])),
                ('auth_p_email_id', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email')])),
                ('auth_id', models.FileField(blank=True, null=True, upload_to='auth_ids/')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_person', to='company_app.s_company')),
            ],
        ),
    ]
