# Generated by Django 5.2.3 on 2026-01-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0002_alter_auth_personal_details_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_company',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='PENDING', max_length=15),
        ),
    ]
