# Generated by Django 5.2.3 on 2026-01-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0003_alter_s_company_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_company',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=15),
        ),
    ]
