# Generated by Django 6.0 on 2025-12-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Housecrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_service', models.CharField(max_length=100)),
                ('h_location', models.CharField(max_length=50)),
            ],
        ),
    ]
