# Generated by Django 6.0 on 2025-12-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housecrew',
            name='h_location',
        ),
    ]
