# Generated by Django 6.0 on 2025-12-22 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_housecrew_h_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='S_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='housecrew',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.s_category'),
        ),
    ]
