# Generated by Django 6.0 on 2026-01-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_location_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housecrew',
            name='category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='location',
        ),
        migrations.DeleteModel(
            name='S_Category',
        ),
        migrations.DeleteModel(
            name='Housecrew',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
