# Generated by Django 6.0 on 2026-01-15 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_housecrew_is_emergency'),
        ('user_app', '0009_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.housecrew'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.addservices'),
        ),
    ]
