# Generated by Django 6.0 on 2026-01-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_booking_crew_booking_is_emergency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
