# Generated by Django 6.0 on 2026-01-16 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0001_initial'),
        ('user_app', '0011_booking_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company_app.s_company'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('COMPLETED', 'completed')], default='PENDING', max_length=15),
        ),
    ]
