# Generated by Django 6.0 on 2026-01-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_booking_company_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('allocated', 'allocated'), ('completed', 'completed'), ('rejected', 'rejected')], default='PENDING', max_length=15),
        ),
    ]
