# Generated by Django 5.2.3 on 2026-01-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_alter_booking_id_alter_callbackrequest_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('allocated', 'allocated'), ('completed', 'completed'), ('rejected', 'rejected'), ('cancelled', 'cancelled')], default='pending', max_length=15),
        ),
    ]
